replicaCount: 2

image:
  repository: summaryexperts/flask-ai-app
  tag: 8f778991128b3180ba9ceb71ce5eb729b20895d2
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80

containerPort: 5000

resources: {}
serviceAccount:
  create: true
  name: ""
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: flask.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
